services:
  backend_service:
    container_name: nexus_backend_container
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure:10
    depends_on:
      - postgres_db_service

  postgres_db_service:
    container_name: nexus_database_container
    image: postgres:13
    volumes:
      - ./data-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"

  frontend_service:
    container_name: nexus_frontend_container
    build: ../../Frontend/nexus
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend_service