from .applicant import ApplicantViewSet
from .current_user import CurrentUserViewSet
from .interview_marks import InterviewMarksView
from .interview_section import InterviewSectionViewSet
from .interview import InterviewViewSet
from .members import MemberViewSet
from .panel import PanelViewSet
from .question import QuestionViewset
from .round_details import RoundViewset
from .round_interview_list import RoundInterviewViewSet
from .round_interview_sections import RoundInterviewSectionViewSet
from .round_names import RoundNameViewSet
from .season import SeasonViewSet
from .section_marks import SectionMarksViewSet
from .test_list import TestApplicantViewSet
from .test_score import TestScoreView
from .test_sections import TestSectionViewset
from .section import SectionViewSet
from .remarks import RemarksView