# Generated by Django 4.1.1 on 2022-09-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('I', 'Interview'), ('T', 'Test')], default='noble', max_length=1),
            preserve_default=False,
        ),
    ]
