# Generated by Django 4.1.1 on 2022-12-25 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgmember',
            name='role',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='section_marks',
        ),
        migrations.AddField(
            model_name='imgmember',
            name='image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='imgmember',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('I', 'Interview'), ('T', 'Test')], default='I', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionmarks',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_marks_set', to='nexus_app.interview'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='role',
            field=models.CharField(choices=[('dev', 'Developer'), ('des', 'Designer')], max_length=3),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='round',
            field=models.ManyToManyField(blank=True, related_name='applicants', related_query_name='applicant', to='nexus_app.round'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nexus_app.round'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Evaluated', 'Evaluated'), ('Not Evaluated', 'Not Evaluated'), ('Called', 'Called'), ('Not Called', 'Not Called')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imgmember',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imgmember',
            name='enrolment_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imgmember',
            name='year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nexus_app.panel'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='nexus_app.round'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='time_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='time_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewsection',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sections', to='nexus_app.round'),
        ),
        migrations.RemoveField(
            model_name='panel',
            name='members',
        ),
        migrations.AlterField(
            model_name='panel',
            name='status',
            field=models.CharField(choices=[('Busy', 'Busy'), ('Vacant', 'Vacant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='assignee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='nexus_app.question'),
        ),
        migrations.AlterField(
            model_name='score',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='nexus_app.round'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus_app.interview')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='panel',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
