# Generated by Django 4.1.1 on 2022-12-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0002_remove_imgmember_role_remove_interview_section_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('I', 'Interview'), ('T', 'Test')], max_length=1),
        ),
    ]
