# Generated by Django 4.1.1 on 2022-09-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0003_alter_imgmember_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='nexus_app.round'),
        ),
    ]
