# Generated by Django 4.1.1 on 2022-09-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0004_alter_test_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='section_marks',
        ),
        migrations.AddField(
            model_name='sectionmarks',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_marks_set', to='nexus_app.interview'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='nexus_app.round'),
        ),
        migrations.AlterField(
            model_name='interviewsection',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sections', to='nexus_app.round'),
        ),
    ]
