# Generated by Django 4.1.1 on 2022-09-24 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0005_remove_interview_section_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='members',
        ),
        migrations.AddField(
            model_name='panel',
            name='members',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
