# Generated by Django 4.1.1 on 2022-09-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0006_remove_panel_members_panel_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nexus_app.panel'),
        ),
    ]
