# Generated by Django 4.1.1 on 2022-09-25 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0008_alter_question_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='assignee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
