# Generated by Django 4.1.1 on 2022-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0009_alter_question_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
