# Generated by Django 4.1.1 on 2022-09-25 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0010_alter_score_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
