# Generated by Django 4.1.1 on 2022-09-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0011_alter_panel_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='round',
            field=models.ManyToManyField(blank=True, related_name='applicants', related_query_name='applicant', to='nexus_app.round'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='stage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
