# Generated by Django 4.1.1 on 2022-09-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0013_remove_imgmember_role_imgmember_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmember',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
