# Generated by Django 4.1.1 on 2022-10-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0015_imgmember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('I', 'Interview'), ('T', 'Test')], max_length=10),
        ),
    ]
