# Generated by Django 4.1.1 on 2022-10-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0017_alter_round_round_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_type',
            field=models.TextField(choices=[('I', 'Interview'), ('T', 'Test')]),
        ),
    ]
