# Generated by Django 4.1.1 on 2022-10-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0019_alter_round_round_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='time_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='time_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
