# Generated by Django 4.1.1 on 2022-10-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0020_alter_interview_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='status',
            field=models.CharField(choices=[('Busy', 'Busy'), ('Vacant', 'Vacant')], max_length=50),
        ),
    ]
