# Generated by Django 4.1.1 on 2022-11-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_app', '0022_alter_interview_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
